resolver: lts-23.0

extra-deps:
- git: https://github.com/KaneTW/haskell-src-exts-qq.git
  commit: 3c68481a457d37d3b610cb4c745d07f85ae9bba7
- git: https://github.com/achirkin/haskell-src-exts-sc.git
  commit: cc0e0f8e86814519281805da610d87cc34c86bea

require-stack-version: ">=1.7"

nix:
  enable: true
